# -*- coding: utf-8 -*-
"""modelo_n.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1beeo1-sgi-OsJz6-a5msEJrs-n6RKqLh
"""

def clasificar_estado_salud_sin_presion(sintomas, temperatura, edad, sexo, frecuencia_cardiaca):
    """
    Clasifica el estado de salud basado en síntomas, temperatura, edad, sexo y frecuencia cardiaca.
    NO incluye la presión arterial.
    Esta es una simulación y NO debe usarse para diagnóstico médico real.

    Args:
        sintomas (list): Lista de hasta 3 strings describiendo síntomas.
        temperatura (float): Temperatura corporal en grados Celsius.
        edad (int): Edad en años.
        sexo (str): "masculino" o "femenino".
        frecuencia_cardiaca (int): Pulsaciones por minuto.

    Returns:
        str: Etiqueta: "NO ENFERMO", "ENFERMEDAD LEVE", "ENFERMEDAD AGUDA", "ENFERMEDAD CRÓNICA".
    """

    # 1. Validar entradas
    if not isinstance(sintomas, list):
        return "Error: Los síntomas deben ser una lista."
    if not isinstance(temperatura, (int, float)):
        return "Error: La temperatura debe ser un número."
    if not isinstance(edad, int) or edad < 0 or edad > 120 :
        return "Error: Edad inválida."
    if not isinstance(sexo, str) or sexo.lower().strip() not in ["masculino", "femenino"]:
        return "Error: Sexo inválido. Usar 'masculino' o 'femenino'."
    if not isinstance(frecuencia_cardiaca, int) or frecuencia_cardiaca < 30 or frecuencia_cardiaca > 250:
         return "Error: Frecuencia cardíaca inválida."

    sintomas_norm = [s.lower().strip() for s in sintomas if isinstance(s, str)]
    sexo_norm = sexo.lower().strip()

    # --- Lógica de decisión basada en condicionales ---

    # Factores de riesgo por edad (simplificado)
    es_vulnerable_edad = (edad < 5 or edad > 65)

    # Umbrales de Frecuencia Cardíaca (muy simplificado)
    fc_normal_alta = 100
    fc_taquicardia_leve = 120
    fc_taquicardia_aguda = 140
    fc_bradicardia_sintomatica = 50 # FC por debajo de la cual, con síntomas, es preocupante

    if edad < 1: # Bebés
        fc_normal_alta = 160
        fc_taquicardia_leve = 180
        fc_taquicardia_aguda = 200
    elif edad < 6: # Niños pequeños
        fc_normal_alta = 140
        fc_taquicardia_leve = 160
        fc_taquicardia_aguda = 180
    elif edad < 12: # Niños
        fc_normal_alta = 120
        fc_taquicardia_leve = 140
        fc_taquicardia_aguda = 160

    # A. Condiciones para ENFERMEDAD CRÓNICA
    # (Prioridad si se cumplen ciertos criterios, incluso con síntomas agudos leves)
    sintomas_cronicos_clave = ["fatiga persistente", "dolor crónico", "pérdida de peso inexplicable gradual",
                               "asma", "diabetes conocida", "hipertensión diagnosticada",
                               "enfermedad pulmonar obstructiva crónica", "epoc"]
    tiene_sintoma_cronico_clave = any(sc in " ".join(sintomas_norm) for sc in sintomas_cronicos_clave)

    if "hipertensión diagnosticada" in sintomas_norm:
        return "ENFERMEDAD CRÓNICA"
    if "diabetes conocida" in sintomas_norm and ("sed excesiva" in sintomas_norm or "micción frecuente" in sintomas_norm or "visión borrosa gradual" in sintomas_norm):
        return "ENFERMEDAD CRÓNICA"
    if ("asma" in sintomas_norm or "epoc" in sintomas_norm or "enfermedad pulmonar obstructiva crónica" in sintomas_norm) and \
       ("tos frecuente" in sintomas_norm or "dificultad leve para respirar habitual" in sintomas_norm or "sibilancias" in sintomas_norm):
        if temperatura < 38.0: # Menos probable que sea una infección aguda si la fiebre no es alta
            return "ENFERMEDAD CRÓNICA"

    # Edad avanzada con síntomas sugerentes de cronicidad y sin fiebre alta
    if edad > 70 and not (temperatura > 38.5): # Si no hay fiebre alta que sugiera agudo
        if ("fatiga persistente" in sintomas_norm or "dolor crónico articular" in sintomas_norm or "movilidad reducida progresiva" in sintomas_norm) and len(sintomas_norm) >=1:
             return "ENFERMEDAD CRÓNICA"
        # Si tiene 2+ síntomas leves y FC algo alterada, y es mayor.
        if len(sintomas_norm) >= 2 and (frecuencia_cardiaca > fc_normal_alta + 10 or frecuencia_cardiaca < 55):
            sintomas_leves_comunes = ["cansancio", "dolor leve", "malestar general"]
            if any(slc in " ".join(sintomas_norm) for slc in sintomas_leves_comunes):
                return "ENFERMEDAD CRÓNICA" # Podría ser deterioro general crónico

    # B. Condiciones para ENFERMEDAD AGUDA
    sintomas_agudos_clave = ["dificultad para respirar severa", "dolor en el pecho opresivo", "dolor en el pecho irradiado",
                             "confusión aguda", "desorientación súbita", "vómitos persistentes e intensos",
                             "fiebre muy alta", "pérdida de conciencia", "incapacidad para moverse", "convulsiones"]
    tiene_sintoma_agudo_clave = any(sa in " ".join(sintomas_norm) for sa in sintomas_agudos_clave)

    if temperatura >= 39.5 or (es_vulnerable_edad and temperatura >= 39.0): # Fiebre muy alta, o alta en vulnerables
        return "ENFERMEDAD AGUDA"
    if tiene_sintoma_agudo_clave:
        return "ENFERMEDAD AGUDA"
    if frecuencia_cardiaca > fc_taquicardia_aguda: # Taquicardia severa
        if len(sintomas_norm) > 0 or temperatura > 38.0: # Con síntomas o fiebre
             return "ENFERMEDAD AGUDA"
    if frecuencia_cardiaca < fc_bradicardia_sintomatica and ("mareo intenso" in sintomas_norm or "debilidad extrema" in sintomas_norm or "pérdida de conciencia" in sintomas_norm or "confusión" in sintomas_norm): # Bradicardia sintomática
        return "ENFERMEDAD AGUDA"
    # Dolor en el pecho con factores de riesgo/acompañantes (sin presión, se enfoca en FC y edad)
    if ("dolor en el pecho opresivo" in sintomas_norm or "dolor en el pecho irradiado" in sintomas_norm) and \
       (edad > 40 or frecuencia_cardiaca > fc_taquicardia_leve or "sudoración fría" in sintomas_norm or "náuseas intensas" in sintomas_norm):
        return "ENFERMEDAD AGUDA"
    # Vulnerables con múltiples síntomas y vitales alterados
    if es_vulnerable_edad and len(sintomas_norm) >=2 and (temperatura > 38.0 or frecuencia_cardiaca > fc_taquicardia_leve):
        # Chequear que no sean síntomas muy leves que podrían ser crónicos
        if not ("fatiga persistente" in sintomas_norm and temperatura < 38.5): # Evitar clasificar como agudo un crónico leve en anciano
            return "ENFERMEDAD AGUDA"


    # C. Condiciones para ENFERMEDAD LEVE
    sintomas_leves_clave = ["tos", "dolor de garganta", "congestión nasal", "dolor de cabeza leve",
                            "malestar general", "fiebre leve", "dolor muscular leve", "fatiga leve", "estornudos"]
    num_sintomas_leves = sum(1 for s_leve in sintomas_leves_clave if s_leve in " ".join(sintomas_norm))

    if temperatura >= 37.8 and temperatura < 39.0 : # Fiebre leve a moderada (sin ser ya AGUDA por vulnerabilidad)
        if len(sintomas_norm) > 0 or frecuencia_cardiaca > fc_normal_alta : # Cualquier síntoma o FC algo elevada con fiebre
            return "ENFERMEDAD LEVE"

    if num_sintomas_leves >= 1:
        if temperatura > 37.2 or (frecuencia_cardiaca > fc_normal_alta and frecuencia_cardiaca <= fc_taquicardia_leve): # Síntomas leves con ligera alteración de temp/FC
            return "ENFERMEDAD LEVE"
        if num_sintomas_leves >=2: # Múltiples síntomas leves incluso con vitales "normales"
            return "ENFERMEDAD LEVE"

    # Si hay algún síntoma reportado y no es agudo/crónico, y los vitales están levemente alterados
    if len(sintomas_norm) > 0:
        if (temperatura > 37.2 and temperatura < 37.8) or \
           (frecuencia_cardiaca > fc_normal_alta and frecuencia_cardiaca <= fc_taquicardia_leve):
            return "ENFERMEDAD LEVE"


    # D. Condiciones para NO ENFERMO
    if temperatura <= 37.2 and (frecuencia_cardiaca >= fc_bradicardia_sintomatica and frecuencia_cardiaca <= fc_normal_alta):
        if not sintomas_norm: # Sin síntomas y vitales normales
            return "NO ENFERMO"
        if len(sintomas_norm) == 1 and ("cansancio ligero puntual" in sintomas_norm or "un poco de sueño" in sintomas_norm):
            return "NO ENFERMO"

    # Fallback: Si hay síntomas pero no encajan claramente y no es NO ENFERMO, asumimos LEVE
    if len(sintomas_norm) > 0:
        return "ENFERMEDAD LEVE"

    return "NO ENFERMO"


# --- Ejemplos de Uso (sin presión) ---
if __name__ == "__main__":
    print("--- Casos de Prueba Detallados (Sin Presión Arterial) ---")

    # Caso 1: Persona sana adulta
    r = clasificar_estado_salud_sin_presion(sintomas=[], temperatura=36.8, edad=30, sexo="masculino", frecuencia_cardiaca=70)
    print(f"1. Adulto Sano: {r}")

    # Caso 2: Resfriado común en adulto
    r = clasificar_estado_salud_sin_presion(sintomas=["tos", "congestión nasal"], temperatura=37.9, edad=35, sexo="femenino", frecuencia_cardiaca=85)
    print(f"2. Resfriado Adulto: {r}")

    # Caso 3: Gripe fuerte en adulto mayor
    r = clasificar_estado_salud_sin_presion(sintomas=["fiebre muy alta", "dolor muscular intenso", "mucha tos"], temperatura=39.2, edad=70, sexo="masculino", frecuencia_cardiaca=110)
    print(f"3. Gripe Adulto Mayor: {r}")

    # Caso 4: Hipertensión crónica (diagnosticada) con síntomas leves
    r = clasificar_estado_salud_sin_presion(sintomas=["fatiga persistente", "dolor de cabeza ocasional", "hipertensión diagnosticada"], temperatura=37.1, edad=55, sexo="femenino", frecuencia_cardiaca=75)
    print(f"4. Hipertensión Crónica (diagnosticada): {r}")

    # Caso 5: Síntomas agudos severos (antes crisis hipertensiva, ahora por síntomas graves)
    r = clasificar_estado_salud_sin_presion(sintomas=["dolor de cabeza intenso y súbito", "visión borrosa severa", "confusión aguda"], temperatura=37.5, edad=60, sexo="masculino", frecuencia_cardiaca=95)
    print(f"5. Síntomas Agudos Severos: {r}")

    # Caso 6: Niño pequeño con fiebre alta y taquicardia
    r = clasificar_estado_salud_sin_presion(sintomas=["llanto constante", "rechazo alimento", "fiebre"], temperatura=39.6, edad=2, sexo="masculino", frecuencia_cardiaca=170)
    print(f"6. Niño Pequeño Agudo: {r}")

    # Caso 7: Asma crónica en joven
    r = clasificar_estado_salud_sin_presion(sintomas=["asma", "tos frecuente por las mañanas", "sibilancias ocasionales"], temperatura=37.0, edad=25, sexo="femenino", frecuencia_cardiaca=80)
    print(f"7. Asma Crónica: {r}")

    # Caso 8: Solo un síntoma leve, vitales casi normales, adulto joven
    r = clasificar_estado_salud_sin_presion(sintomas=["dolor de cabeza leve"], temperatura=37.3, edad=22, sexo="masculino", frecuencia_cardiaca=78)
    print(f"8. Síntoma Leve Aislado: {r}")

    # Caso 9: Persona mayor con síntomas crónicos
    r = clasificar_estado_salud_sin_presion(sintomas=["fatiga persistente", "dolor crónico articular"], temperatura=37.2, edad=75, sexo="femenino", frecuencia_cardiaca=80) # FC normal para que no sea agudo
    print(f"9. Mayor con síntomas crónicos: {r}")

    # Caso 10: Dolor en el pecho sospechoso en hombre de mediana edad con taquicardia
    r = clasificar_estado_salud_sin_presion(sintomas=["dolor en el pecho opresivo", "sudoración fría"], temperatura=37.0, edad=58, sexo="masculino", frecuencia_cardiaca=115)
    print(f"10. Dolor Pecho Sospechoso: {r}")

    # Caso 11: Adulto con bradicardia y mareos
    r = clasificar_estado_salud_sin_presion(sintomas=["mareo intenso", "debilidad extrema"], temperatura=36.5, edad=40, sexo="masculino", frecuencia_cardiaca=45)
    print(f"11. Bradicardia Sintomática: {r}")

    # Caso 12: Bebé aparentemente sano
    r = clasificar_estado_salud_sin_presion(sintomas=[], temperatura=37.0, edad=0, sexo="femenino", frecuencia_cardiaca=130)
    print(f"12. Bebé Sano: {r}")

    # Caso 13: Error de entrada (frecuencia cardíaca)
    r = clasificar_estado_salud_sin_presion(sintomas=[], temperatura=37.0, edad=30, sexo="masculino", frecuencia_cardiaca=20)
    print(f"13. Error FC: {r}")

    # Caso 14: Adulto mayor, 2 síntomas leves, FC un poco elevada, sin fiebre alta
    r = clasificar_estado_salud_sin_presion(sintomas=["cansancio", "dolor leve generalizado"], temperatura=37.1, edad=78, sexo="femenino", frecuencia_cardiaca=105)
    print(f"14. Mayor, 2 síntomas leves, FC un poco alta: {r}") # Podría ser LEVE o CRÓNICA dependiendo de la interpretación de la regla.